Add proper localization logic for getByIdQuery
NoxOrg/Nox pull request #1068
Opened 2023-10-30 12:53 UTC by ILoveMyTortoise

closes #938

2023-10-30 17:19 UTC, rochar requested changes
looks good, just a small improvement

2023-10-30 17:19 UTC, rochar commented on src/Nox.ClientApi.Tests/Generated/Nox.Generator/Nox.Generator.NoxCodeGenerator/Application.Queries/GetWorkplaceByIdQuery.g.cs
> +public record GetWorkplaceByIdQuery(string cultureCode, System.UInt32 keyId) : IRequest <IQueryable<WorkplaceDto>>;
I just notice now, Culture code should be a Nox.Type.CultureCode, we need also to update the GetQuery
This will enforce valid culture codes

2023-10-31 09:00 UTC, ILoveMyTortoise commented on src/Nox.ClientApi.Tests/Generated/Nox.Generator/Nox.Generator.NoxCodeGenerator/Application.Queries/GetWorkplaceByIdQuery.g.cs
> +public record GetWorkplaceByIdQuery(string cultureCode, System.UInt32 keyId) : IRequest <IQueryable<WorkplaceDto>>;
Done

2023-11-02 15:12 UTC, rochar approved these changes, later dismissed

2023-11-03 08:24 UTC, rochar submitted a review, later dismissed

2023-11-03 10:13 UTC, gjorgji-grgovski-authoritypartners reviewed
Looks good, just few small comments

2023-11-03 10:13 UTC, gjorgji-grgovski-authoritypartners commented on src/Nox.Generator/Application/Queries/ByIdQueryLocalized.template.cs
> +public record Get{{entity.Name }}ByIdQuery(CultureCode cultureCode, {{primaryKeys}}) : IRequest <IQueryable<{{entity.Name}}Dto>>;
```suggestion
public record {{className}}(CultureCode cultureCode, {{primaryKeys}}) : IRequest <IQueryable<{{entity.Name}}Dto>>;
```

2023-11-03 10:13 UTC, gjorgji-grgovski-authoritypartners commented on src/Nox.Generator/Application/Queries/ByIdQueryLocalized.template.cs
> +internal partial class Get{{entity.Name}}ByIdQueryHandler:Get{{entity.Name}}ByIdQueryHandlerBase
```suggestion
internal partial class {{className}}Handler: {{className}}HandlerBase
```

2023-11-03 10:13 UTC, gjorgji-grgovski-authoritypartners commented on src/Nox.Generator/Application/Queries/ByIdQueryLocalized.template.cs
> +    public  Get{{entity.Name}}ByIdQueryHandler(DtoDbContext dataDbContext): base(dataDbContext)
```suggestion
    public  {{className}}Handler(DtoDbContext dataDbContext): base(dataDbContext)
```

2023-11-03 10:13 UTC, gjorgji-grgovski-authoritypartners commented on src/Nox.Generator/Application/Queries/ByIdQueryLocalized.template.cs
> +internal abstract class Get{{entity.Name}}ByIdQueryHandlerBase:  QueryBase<IQueryable<{{entity.Name}}Dto>>, IRequestHandler<Get{{entity.Name}}ByIdQuery, IQueryable<{{entity.Name}}Dto>>
```suggestion
internal abstract class {{className}}HandlerBase:  QueryBase<IQueryable<{{entity.Name}}Dto>>, IRequestHandler<{{className}}, IQueryable<{{entity.Name}}Dto>>
```

2023-11-03 10:13 UTC, gjorgji-grgovski-authoritypartners commented on src/Nox.Generator/Application/Queries/ByIdQueryLocalized.template.cs
> +    public  Get{{entity.Name}}ByIdQueryHandlerBase(DtoDbContext dataDbContext)
```suggestion
    public  {{className}}HandlerBase(DtoDbContext dataDbContext)
```

2023-11-03 10:13 UTC, gjorgji-grgovski-authoritypartners commented on src/Nox.Generator/Application/Queries/ByIdQueryLocalized.template.cs
> +    public virtual Task<IQueryable<{{entity.Name}}Dto>> Handle(Get{{entity.Name}}ByIdQuery request, CancellationToken cancellationToken)
```suggestion
    public virtual Task<IQueryable<{{entity.Name}}Dto>> Handle({{className}} request, CancellationToken cancellationToken)
```

2023-11-03 10:13 UTC, gjorgji-grgovski-authoritypartners commented on src/Nox.ClientApi.Tests/Tests/Controllers/WorkplacesControllerTests.cs
> +                Description = _fixture.Create<string>(),
Can we have a hardcoded Description here, and check the exact value of the Description, I can always create a workplace with a Description=[Test] and this test would pass.

2023-11-03 10:13 UTC, gjorgji-grgovski-authoritypartners commented on src/Nox.ClientApi.Tests/Tests/Controllers/WorkplacesControllerTests.cs
> +            localizedWorkplaces.Description.Should().StartWith("[");
```suggestion
            localizedWorkplaces.Description.Should().BeEquivalentTo($"[{description}]");
```

2023-11-03 12:24 UTC, gjorgji-grgovski-authoritypartners approved these changes

2023-11-03 13:56 UTC, rochar approved these changes

2023-11-03 13:56 UTC, merged