NOX-36 - PartialUpdate<Entity>Command save to Localized table
NoxOrg/Nox pull request #1076
Opened 2023-11-02 09:22 UTC by dejobratic

2023-11-08 16:14 UTC, rochar requested changes
looks good, please catch up with @ggrgovski  you just need to do the change regarding the property name "withAttributes"

2023-11-08 16:14 UTC, rochar commented on src/Nox.Generator/Application/Factories/EntityLocalizedFactory.template.cs
> +    public virtual {{localizedEntityName}} CreateLocalizedEntity({{entity.Name}}Entity entity, CultureCode cultureCode, bool withAttributes = true)
For better readability:

```suggestion
    public virtual {{localizedEntityName}} CreateLocalizedEntity({{entity.Name}}Entity entity, CultureCode cultureCode, bool copyEntityAttributes= true)
```

2023-11-08 16:14 UTC, rochar commented on src/Nox.Solution/Extensions/EntityExtensions.cs
> +        => entity.Attributes.Where(x => x.IsLocalized).Select(property =>
IMO this is a kind of an hack, 
We should change the code according to be a localized or not, for example in EntitLocalized.template should set everything to optional and not use the IsRequired, because that is the rule

2023-11-08 16:14 UTC, rochar commented on src/Nox.Solution/Extensions/EntityExtensions.cs
> +        => entity.Attributes.Where(x => x.IsLocalized).Select(property =>
and in the NoxDatabaseConfigurator. ConfigureLocalizedAttributes you can clone and change the is required, because there it will be explicit that we are configuring the db and set all fields to optional

2023-11-08 16:14 UTC, rochar commented on src/Nox.Generator/Application/Dto/EntityLocalizedDto.template.cs
> +    public {{attributeType attribute}}? {{attribute.Name}} { get; set; }
this is good we are being explicitly here!

2023-11-08 16:14 UTC, rochar commented on src/Nox.Generator/Application/Commands/PartialUpdateOwnedCommand.template.cs
> +		EntityFactory.PartialUpdateEntity(entity, request.UpdatedProperties, DefaultCultureCode);
Owned Entities need also to support localized text fields
We are creating a ticket for handling this

2023-11-09 07:47 UTC, rochar approved these changes

2023-11-09 08:25 UTC, gjorgji-grgovski-authoritypartners approved these changes

2023-11-09 08:25 UTC, merged