Feature/improve abstractions
NoxOrg/Nox pull request #1093
Opened 2023-11-08 09:30 UTC by jan-schutte

2023-11-08 10:01 UTC, AndreyDegtyarev submitted a review, later dismissed

2023-11-09 09:12 UTC, rochar requested changes

2023-11-09 09:12 UTC, rochar commented on samples/Cryptocash.Api/Cryptocash.Api.csproj
> +    <ItemGroup>
This ItemGroup is not required

2023-11-09 09:12 UTC, rochar commented on samples/Cryptocash.Ui/Nox.Generated/Generator.g.cs
> +- generator.nox.yaml
the generator is producing errors for the yaml changes?

2023-11-18 18:30 UTC, closed without merging

2023-11-18 18:30 UTC, rochar commented
obsolete