NOX-29 entitiy translations Create/Update/Read
NoxOrg/Nox pull request #1106
Opened 2023-11-10 18:39 UTC by msadikkoseaupa

2023-11-13 11:34 UTC, rochar requested changes
looks good
some comment, please catch up with @ggrgovski

2023-11-13 11:34 UTC, rochar commented on src/Nox.ClientApi.Tests/Generated/Nox.Generator/Nox.Generator.NoxCodeGenerator/Application.Dto/WorkplaceLocalizedCreateDto.g.cs
shoud we not have a single `<EntityName>LocalizedUpsertDto`?

2023-11-13 11:34 UTC, rochar commented on src/Nox.ClientApi.Tests/Generated/Nox.Generator/Nox.Generator.NoxCodeGenerator/Application.Queries/GetWorkplaceTranslationsByIdQuery.g.cs
> +public record GetWorkplaceTranslationsByIdQuery(System.UInt32 keyId, System.String CultureCode) : IRequest <IQueryable<WorkplaceLocalizedDto>>;
CultureCode must be a Nox.Type.CultureCode, so we benefit from intention and have validations OOB

2023-11-13 11:34 UTC, rochar commented on src/Nox.ClientApi.Tests/Generated/Nox.Generator/Nox.Generator.NoxCodeGenerator/Domain/WorkplaceLocalized.g.cs
> +[PrimaryKey(nameof(Id),nameof(CultureCode))]
we are using the modelcreating in dbcontext to configure dto, we are not using attributes for this, I would prefer to keep consistency on this

2023-11-13 11:34 UTC, rochar commented on src/Nox.ClientApi.Tests/Tests/Controllers/WorkplacesControllerTests.cs
> +            var localizedNew = GetEntitiesByFilter<WorkplaceLocalized>(dto => dto.Id == Nuid.From(result!.Id));
Its this being used?

2023-11-13 11:34 UTC, rochar commented on src/Nox.ClientApi.Tests/Tests/NoxWebApiTestBase.cs
> +    protected List<TResult>? GetEntitiesByFilter<TResult>(Func<TResult, bool> filter) where TResult : class
we need to discuss what is the goal of ClientApi.Tes, accessing directly to the DB, we need to think about this!

2023-11-13 11:34 UTC, rochar commented on src/Nox.ClientApi.Tests/Generated/Nox.Generator/Nox.Generator.NoxCodeGenerator/Application.Commands/CreateWorkplaceTranslationsCommand.g.cs
> +		return new WorkplaceLocalizedKeyDto(entityLocalizedToCreate.Id.Value, entityLocalizedToCreate.CultureCode.Value);
If its the default culture should also update the main entity

2023-11-13 11:34 UTC, rochar commented on src/Nox.ClientApi.Tests/Generated/Nox.Generator/Nox.Generator.NoxCodeGenerator/Presentation.Api.OData/WorkplacesController/Translations.g.cs
@ggrgovski  we miss to define the delete end point, or did we assume put null to be the same as deleted?

When this is completed we need to review the ticket for Get Translations make it consistent with any changes that we agree on this one

2023-11-14 09:56 UTC, msadikkoseaupa commented
This pr won't be used any more, new brand new pr has been created regarding the latest design changes.

2023-11-14 09:56 UTC, closed without merging