NOX-238 Delete all related endpoint must execute a single command
NoxOrg/Nox pull request #1156
Opened 2023-11-22 12:24 UTC by AndreyDegtyarev

Delete all related endpoint must execute a single command

2023-11-22 13:51 UTC, anna-naumova25 commented
@AndreyDegtyarev @rochar do we really want to have these additional commands for each relationship? 

@AndreyDegtyarev can't we just reuse the existing DeleteById command and send the list of Ids as the request? 

Also I don't see where this new command is used in the code. 

And we'll probably need some tests in ClientApiTests to cover it.

2023-11-22 13:51 UTC, anna-naumova25 requested changes

2023-11-22 13:51 UTC, anna-naumova25 commented on src/Nox.Generator/Application/Commands/DeleteRelatedCommand.template.cs
> +public partial record DeleteAll{{relationship.Name}}For{{parent.Name}}Command({{parent.Name}}KeyDto ParentKeyDto) : IRequest <bool>;
It should be used {{GetNavigationPropertyName parent relationship}} instead of {{relationship.Name}}

2023-11-22 13:51 UTC, anna-naumova25 commented on src/Nox.Generator/Application/Commands/DeleteRelatedCommand.template.cs
> +				DbContext.{{relationship.EntityPlural}}.Remove(relatedEntity);
There should be different logic for Auditable entities:

```
{{- if (entity.Persistence?.IsAudited ?? true) }}
DbContext.Entry(entity).State = EntityState.Deleted;
{{-else-}}
DbContext.{{entity.PluralName}}.Remove(entity);
{{- end}}
```

2023-11-22 13:51 UTC, anna-naumova25 commented on src/Nox.Generator/Application/Commands/DeleteRelatedCommandGenerator.cs
> +            foreach (var ownedRelation in entity.Relationships.Where(x => x.WithMultiEntity))
Why is it called `ownedRelation` if it is a normal relation?

2023-11-22 14:15 UTC, rochar commented
> @AndreyDegtyarev @rochar do we really want to have these additional commands for each relationship?
> 
> @AndreyDegtyarev can't we just reuse the existing DeleteById command and send the list of Ids as the request?
> 
> Also I don't see where this new command is used in the code.
> 
> And we'll probably need some tests in ClientApiTests to cover it.

@AndreyDegtyarev  the idea was just to change the current delete command instead of receiving a single entity, would receive a list => We are deleting an entity via the a related end point the command should not care about ii

this is not being called anywhere!!!

2023-11-27 17:07 UTC, rochar commented
we will pick this later

2023-11-27 17:07 UTC, closed without merging