NOX-281 Add Validation for the commands where <OwnedEntity>UpsertDto is used
NoxOrg/Nox pull request #1158
Opened 2023-11-22 15:34 UTC by anna-naumova25

2023-11-22 16:05 UTC, anna-naumova25 commented on src/Nox.Generator/Presentation/Api/OData/EntityControllerGenerator.cs
> +            code.AppendLine($"return BadRequest(\"{child.Keys[0].Name} is required.\");");
Will need to apply latest changes for Exception here once they are merged

2023-11-23 08:25 UTC, rochar requested changes
looks good, lets just discuss some points

2023-11-23 08:25 UTC, rochar commented on src/Nox.Generator/Presentation/Api/OData/EntityControllerGenerator.cs
> +        code.AppendLine($"public virtual async Task<ActionResult<{child.Name}Dto>> PutTo{relationshipName}(" +
we should use the related entity name? to make it consistent with "normal" Relations
for owned we do not have the case of relating to the same entity

And we should keep the plural if ToMany and singular if to one?

We have other issue to rename the OwnedEntitites Navigation properties, and think we should align also the endpoints

2023-11-23 08:25 UTC, rochar commented on src/Nox.Generator/Presentation/Api/OData/EntityControllerGenerator.cs
> +        code.AppendLine($"public virtual async Task<ActionResult<{child.Name}Dto>> PutTo{relationshipName}(" +
Another question, do you think its easy to migrate this to the template for owned, now that you are changing this?

2023-11-23 08:25 UTC, rochar commented on src/Nox.Generator/Application/Factories/EntityFactory.template.cs
> +        entity.{{key.Name}} = {{entity.Name}}Metadata.Create{{key.Name}}(createDto.{{key.Name}}{{if entity.IsOwnedEntity}}.NonNullValue<{{keyType key}}>(){{end}});
now looking to this, we can not have an owned used as a Foreign key, if this is possible in Nox.Solution that is incorrect.

@anna-naumova25  lets discuss this use case

2023-11-27 15:01 UTC, rochar requested changes

2023-11-27 15:01 UTC, rochar commented on src/Nox.Generator/Presentation/Api/OData/EntityControllerGenerator.cs
>          var relationshipName = parent.GetNavigationPropertyName(relationship);
rename to navigationPropertyName

2023-11-27 17:04 UTC, anna-naumova25 commented on src/Nox.Generator/Presentation/Api/OData/EntityControllerGenerator.cs
> +            code.AppendLine($"return BadRequest(\"{child.Keys[0].Name} is required.\");");
done

2023-11-27 17:04 UTC, anna-naumova25 commented on src/Nox.Generator/Presentation/Api/OData/EntityControllerGenerator.cs
>          var relationshipName = parent.GetNavigationPropertyName(relationship);
done

2023-11-27 17:05 UTC, rochar approved these changes

2023-11-27 17:06 UTC, merged