NOX-244 - [Technical Item] Change how DbConfigurator sets Owner Entity relations to Owned Entity and how Owned is configured
NoxOrg/Nox pull request #1165
Opened 2023-11-23 14:28 UTC by dejobratic

2023-11-24 15:15 UTC, rochar requested changes

2023-11-24 15:15 UTC, rochar commented on src/Nox.Generator/Infrastructure/Persistence/DtoDbContext.template.cs
> +                _noxDtoDatabaseConfigurator.ConfigureDto(new EntityBuilderAdapter(modelBuilder.Entity(type).ToTable(entity.PluralName)), entity);
```suggestion
                _noxDtoDatabaseConfigurator.ConfigureDto(new EntityBuilderAdapter(modelBuilder.Entity(type).ToTable(entity.Persistence.TableName)), entity);
```

2023-11-24 15:15 UTC, rochar commented on src/Nox.Generator/Infrastructure/Persistence/DbContext.template.cs
> +            ((INoxDatabaseConfigurator)_dbProvider).ConfigureEntity(modelBuilder, new EntityBuilderAdapter(modelBuilder.Entity(type!).ToTable(entity.PluralName)), entity);
```suggestion
            ((INoxDatabaseConfigurator)_dbProvider).ConfigureEntity(modelBuilder, new EntityBuilderAdapter(modelBuilder.Entity(type!).ToTable(entity.Persistence.TableName)), entity);
```

2023-11-24 16:45 UTC, gjorgji-grgovski-authoritypartners approved these changes

2023-11-25 08:49 UTC, rochar approved these changes

2023-11-25 08:50 UTC, merged