NOX-131 [Nox.Lib] Ensure Events Raised are logged
NoxOrg/Nox pull request #1186
Opened 2023-11-29 17:15 UTC by emir-sehovic1

2023-11-30 23:11 UTC, gjorgji-grgovski-authoritypartners requested changes

2023-11-30 23:11 UTC, gjorgji-grgovski-authoritypartners commented on src/Nox.Lib/Infrastructure/Messaging/OutboxRepository.cs
> +            _logger.LogInformation($"Publishing integration event '{typeof(T)}'. Name: '{eventName}' Source: '{source}'");
Let's extend it with Type and DataSchema.

2023-12-01 10:14 UTC, gjorgji-grgovski-authoritypartners submitted a review, later dismissed

2023-12-04 10:35 UTC, rochar reviewed
looks good just a small change

2023-12-04 10:35 UTC, rochar commented on src/Nox.Lib/Infrastructure/Messaging/OutboxRepository.cs
> +            _logger.LogInformation($"Publishing integration event '{typeof(T)}'. Name: '{eventName}' Source: '{source}' Type: '{type}' DataSchema: '{dataSchema}'");
@emir-sehovic1  take a look to this one https://blog.objektkultur.de/structured-logging-with-.net-ilogger/

We should do this small change?

2023-12-04 15:23 UTC, rochar approved these changes

2023-12-04 15:26 UTC, gjorgji-grgovski-authoritypartners approved these changes

2023-12-04 15:29 UTC, merged