Feature/nox 171 source filtering
NoxOrg/Nox pull request #1200
Opened 2023-12-01 14:56 UTC by jan-schutte

2023-12-06 12:52 UTC, rochar requested changes

2023-12-06 12:52 UTC, rochar commented on .idea/.idea.Nox.Generator.dir/.idea/.gitignore
do you want to commite .idea configuration, maybe add this to the main gitignore only

2023-12-06 12:52 UTC, rochar commented on src/Nox.Generator/Infrastructure/Persistence/DtoDbContext.template.cs
> +{{- if codeGeneratorState.Solution.Domain != null }}
The Generator will not call template if the domain is null

2023-12-06 12:52 UTC, rochar commented on src/Nox.Integration.SqlServer/Extensions/SqlServerIntegrationOptionsExtension.cs
> +        optionsBuilder.Services.AddSingleton<INoxDatabaseProvider>(provider => new SqlServerDatabaseProvider(
like we agree lets have a `IEntityDatabaseProvider: INoxDatabaseProvider`

and `IIntegrationDatabaseProvider: INoxdatabaseProvider` for example

2023-12-12 10:46 UTC, closed without merging

2023-12-12 10:47 UTC, jan-schutte commented
redundant