NOX-238 Delete all related endpoint must execute a single command
NoxOrg/Nox pull request #1201
Opened 2023-12-01 18:30 UTC by anna-naumova25

2023-12-01 18:31 UTC, anna-naumova25 commented on src/Nox.Generator/Application/Commands/DeleteByIdCommand.template.cs
> +		await OnCompletedAsync(request, new {{entity.Name}}Entity());
OnCompletedAsync accepts TRequest and TEntity. What should be sent in this case if we changed List<TEntity>?

2023-12-01 19:17 UTC, gjorgji-grgovski-authoritypartners commented on src/Nox.Generator/Application/Commands/DeleteByIdCommand.template.cs
> +		await OnCompletedAsync(request, new {{entity.Name}}Entity());
@anna-naumova25 @rochar We had a similar situation for the other endpoints and we have introduced the OnCompletedBatchAsync method instead of this one. We can work together next week on this if you have different ideas.

2023-12-04 10:10 UTC, rochar requested changes

2023-12-04 10:10 UTC, rochar commented on src/Nox.Generator/Application/Commands/DeleteByIdCommand.template.cs
> +			{{- if (entity.Persistence?.IsAudited ?? true) }}
there is no diference between  `DbContext.Entry(entity).State = EntityState.Deleted;` and `DbContext.{{entity.PluralName}}.Remove(entity);` we do not need to care if is Auditable at this level, that is an infrastructural concept

2023-12-04 10:10 UTC, rochar commented on src/Nox.Generator/Application/Commands/DeleteByIdCommand.template.cs
> +			{{- if (entity.Persistence?.IsAudited ?? true) }}
in a next iteration we can replace by IRepository...

2023-12-04 10:10 UTC, rochar commented on samples/Cryptocash.Api/Generated/Nox.Generator/Nox.Generator.NoxCodeGenerator/Application.Commands/DeleteBookingByIdCommand.g.cs
> +		await OnCompletedAsync(request, new BookingEntity());
new? Should be the deleted entity

2023-12-04 14:12 UTC, rochar approved these changes

2023-12-04 17:25 UTC, merged