NOX-388 owned entity localization factory
NoxOrg/Nox pull request #1262
Opened 2023-12-18 20:25 UTC by msadikkoseaupa

2023-12-19 12:25 UTC, rochar requested changes

2023-12-19 12:25 UTC, rochar commented on src/Nox.Core/Domain/IEntityConcurrent.cs
> +public interface IEntityConcurrent: IEntity
We should avoid have inheritance on contracts.

2023-12-19 12:25 UTC, rochar commented on src/Nox.Core/Domain/IRepository.cs
> +    IQueryable<T> QueryOwned<T>(Expression<Func<T, bool>> predicate) where T : class, IOwnedEntity;
we  do not need the Owned, I guess it will not work since we do not have any set registered for owned

2023-12-21 16:03 UTC, rochar approved these changes, later dismissed

2023-12-21 16:31 UTC, gjorgji-grgovski-authoritypartners submitted a review, later dismissed

2023-12-21 16:43 UTC, rochar approved these changes

2023-12-21 16:49 UTC, gjorgji-grgovski-authoritypartners approved these changes

2023-12-21 16:49 UTC, merged