NOX-301 Create or Update Owned Entity Translations
NoxOrg/Nox pull request #1323
Opened 2024-01-04 18:58 UTC by emir-sehovic1

2024-01-08 13:36 UTC, anna-naumova25 commented on src/Nox.Docs/Templates/EntityEndpoints.template.md
> +- **PUT** `{{apiRoutePrefix}}/{{entity.PluralName}}/{key}/{{if localizedRelationship.IsWithMultiEntity}}{{localizedRelationship.OwnedEntity.PluralName}}{{else}}{{localizedRelationship.OwnedEntity.Nam
```suggestion
- **PUT** `{{apiRoutePrefix}}/{{entity.PluralName}}/{key}/{{GetNavigationPropertyName entity localizedRelationship}}Localized/{cultureCode}` 
```

2024-01-08 13:40 UTC, anna-naumova25 commented on src/Nox.Generator/Presentation/Api/OData/EntityController.Translations.template.cs
> +    [HttpPut("{{solution.Presentation.ApiConfiguration.ApiRoutePrefix}}/{{entity.PluralName}}/{{keysRoute}}{{if localizedRelationship.IsWithMultiEntity}}{{localizedRelationship.OwnedEntity.PluralName
```suggestion
    [HttpPut("{{solution.Presentation.ApiConfiguration.ApiRoutePrefix}}/{{entity.PluralName}}/{{keysRoute}}{{GetNavigationPropertyName entity localizedRelationship}}Localized/{%{{}%}{{cultureCode}}{%{}}%}")]
```

2024-01-08 13:47 UTC, anna-naumova25 requested changes
Just several comments.

2024-01-09 10:39 UTC, emir-sehovic1 commented
> Just several comments.

Thanks @anna-naumova25 , I've added the changes

2024-01-09 13:37 UTC, anna-naumova25 submitted a review, later dismissed

2024-01-09 15:47 UTC, gjorgji-grgovski-authoritypartners approved these changes, later dismissed

2024-01-09 16:04 UTC, gjorgji-grgovski-authoritypartners submitted a review, later dismissed

2024-01-10 13:17 UTC, anna-naumova25 approved these changes

2024-01-10 13:21 UTC, gjorgji-grgovski-authoritypartners approved these changes

2024-01-10 13:21 UTC, merged