NOX-290 Delete Entity and Owned Localized Translations
NoxOrg/Nox pull request #1348
Opened 2024-01-12 09:26 UTC by emir-sehovic1

2024-01-16 14:27 UTC, rochar requested changes

2024-01-16 14:27 UTC, rochar commented on src/Nox.Lib/Extensions/IQueryableExtensions.cs
All code that is not WebApi related should be moved to Nox.Core

2024-01-17 08:53 UTC, rochar requested changes

2024-01-17 08:53 UTC, rochar commented on src/Nox.Lib/Extensions/IQueryableExtensions.cs
actually I'm not finding any usage of this extension?

2024-01-17 09:10 UTC, emir-sehovic1 commented on src/Nox.Lib/Extensions/IQueryableExtensions.cs
@rochar It is used in the template [src/Nox.Generator/Application/Commands/DeleteOwnedEntityTranslationsCommand.template.cs](https://github.com/NoxOrg/Nox/pull/1348/files#diff-e48fdae6336ecd13e726b2301880db8c10475e2c5d40f5c72320244eee87428c:~:text=%7B%7Bentity.PluralName%7D%7DLocalized.WhereAnyMatch)
at line 74

2024-01-17 09:46 UTC, rochar commented on src/Nox.Lib/Extensions/IQueryableExtensions.cs
ok thks, it's on the Scriban Template, that why I did not find it!

2024-01-17 11:05 UTC, rochar requested changes

2024-01-17 11:05 UTC, rochar commented on src/Nox.Core/Exceptions/EntityNotFoundException.cs
> +    public EntityNotFoundException(string entityName, string entityId, string cultureCode)
In this case we did not found the entity or the localized text for that culture
IMO we should create a specific exception for this, so its clear that we did not found the localized text, for example: `EntityLocalizedTextNotFound`

2024-01-17 11:05 UTC, rochar commented on src/Nox.Generator/Application/Commands/DeleteOwnedEntityTranslationsCommand.template.cs
> +        var entities = await DbContext.{{entity.PluralName}}Localized.WhereAnyMatch(entityKeys, (x,y) => {{for key in entity.Keys}}x.{{key.Name}} == {{key.Name}} && {{end}}x.CultureCode == command.Cu
can you add an example to ClientApi.tests, so we have a owner entity related to Many Owned Entity, that contains localized text, and is using WhereAnyMatch? thks

2024-01-17 11:05 UTC, rochar commented on tests/Nox.ClientApi.Tests/Generated/Nox.Generator/Nox.Generator.NoxCodeGenerator/Application.Commands/DeleteTenantBrandsTranslationsForTenantCommand.g.cs
> +            throw new EntityNotFoundException("Tenant", $"{parentKeyId.ToString()}");
I would suggest to add a Guard to EntityNotFoundException to do this, and avoid the branching on the code... I know we are doing this in other parts, but this a is a good opportunity to improve.

EntityNotFoundException.ThrowIfNull(parentEntity, "Tenant", $"{parentKeyId.ToString()}")

2024-01-17 11:05 UTC, rochar commented on src/Nox.Generator/Application/Commands/DeleteOwnedEntityTranslationsCommand.template.cs
> +        var entities = await DbContext.{{entity.PluralName}}Localized.WhereAnyMatch(entityKeys, (x,y) => {{for key in entity.Keys}}x.{{key.Name}} == {{key.Name}} && {{end}}x.CultureCode == command.Cu
We do not support this use case, for example, changing TenantBrands key to be a composite key:

`//  - The Nox type validation failed with 1 error(s). PropertyName: TenantBrands. Error: Relationship [TenantBrands] on entity [Tenant] refers to related entity [TenantBrand] with composite key. Must be simple key on TenantBrand.   at Nox.Yaml.YamlConfigurationReader`2.ValidateAll(TFullType instance) in ....YamlConfigurationReader.cs:line 239`

2024-01-18 12:12 UTC, emir-sehovic1 commented on src/Nox.Generator/Application/Commands/DeleteOwnedEntityTranslationsCommand.template.cs
> +        var entities = await DbContext.{{entity.PluralName}}Localized.WhereAnyMatch(entityKeys, (x,y) => {{for key in entity.Keys}}x.{{key.Name}} == {{key.Name}} && {{end}}x.CultureCode == command.Cu
@rochar  yes, currently compound keys are not supported when dealing with owned relationships, however I noticed that rest of the templates were written without that assumption, I suppose for purpose of easier upgrade if this feature will be supported at some point. So I opted to write this template in that way as well. Let me know if you would still prefer me to delete this case.

2024-01-19 09:38 UTC, rochar commented on src/Nox.Generator/Application/Commands/DeleteOwnedEntityTranslationsCommand.template.cs
> +        var entities = await DbContext.{{entity.PluralName}}Localized.WhereAnyMatch(entityKeys, (x,y) => {{for key in entity.Keys}}x.{{key.Name}} == {{key.Name}} && {{end}}x.CultureCode == command.Cu
I would prefer to follow the Yagni principle in this case. Because we do not have any plans to support this.

2024-01-19 14:24 UTC, anna-naumova25 approved these changes

2024-01-19 14:27 UTC, rochar approved these changes

2024-01-19 14:30 UTC, merged