NOX-576 Nox Type Extensions for PhoneNumber
NoxOrg/Nox pull request #1361
Opened 2024-01-16 14:52 UTC by msadikkoseaupa

2024-01-16 15:18 UTC, rochar submitted a review, later dismissed

2024-01-16 15:18 UTC, rochar commented on src/Nox.Types.Extensions/Types/PhoneNumber/PhoneNumberExtensions.cs
we just simplified the extensions structure, can y move the extension file to the root of the project? thanks

2024-01-16 15:18 UTC, gjorgji-grgovski-authoritypartners submitted a review, later dismissed

2024-01-16 19:13 UTC, msadikkoseaupa commented on src/Nox.Types.Extensions/Types/PhoneNumber/PhoneNumberExtensions.cs
Desired changes have been applied

2024-01-17 08:56 UTC, rochar requested changes

2024-01-17 08:56 UTC, rochar commented on samples/Cryptocash.Ui/Nox.Generated/Generator.g.cs
Build explicitly the Nox.Generator.Task (you have an old version in cache) - See readme file if the output dll file is locked by VS

this will allow to generate the code properly. 

Thks

2024-01-17 09:43 UTC, msadikkoseaupa commented on samples/Cryptocash.Ui/Nox.Generated/Generator.g.cs
Desired changes have been applied

2024-01-17 09:44 UTC, rochar submitted a review, later dismissed

2024-01-17 11:01 UTC, rochar approved these changes

2024-01-17 11:01 UTC, gjorgji-grgovski-authoritypartners approved these changes

2024-01-17 11:01 UTC, merged