NOX-657 add entity services
NoxOrg/Nox pull request #1399
Opened 2024-01-29 18:59 UTC by anna-naumova25

2024-01-30 08:47 UTC, DanielHodgeGH approved these changes, later dismissed
Thanks @anna-naumova25 looks good - the only thing for me - which we need to discuss is the GetAllAsync - I think should use SEARCHFILTER and ORDERBY options to build on the fly GET ODATA querys to filter and order the returning dataset - but this needs to be agreed for a future PR probably - thanks DanHo

2024-01-30 13:44 UTC, rochar requested changes

2024-01-30 13:44 UTC, rochar commented on src/Nox.Generator.Tasks/Ui/Extensions/ServiceCollectionExtension.scriban-cs
> +        services.AddSingleton<GlobalDataService>();
@anna-naumova25 lets rename GlobalDataService, I always need to open it to understand what is the goal of it :)

maybe?
```suggestion
        services.AddSingleton<ApplicationState>();
```

2024-01-30 13:44 UTC, rochar commented on src/Nox.Generator.Tasks/Ui/Extensions/ServiceCollectionExtension.scriban-cs
> +        services.AddMudServices();
@anna-naumova25  can you take a look at this https://learn.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests

and review if we can make this more resilient?

2024-01-30 13:44 UTC, rochar commented on samples/Cryptocash.Ui/Nox.Generated/Ui.Extensions/ServiceCollectionExtension.g.cs
> +        services.AddScoped<EndpointsProvider>();
this one can be singleton? never changes?

2024-01-30 13:44 UTC, rochar commented on samples/Cryptocash.Ui/Nox.Generated/Ui.Services/EndpointsProvider.g.cs
> +        get { return $"{BaseUrl}/api"; }
We should consider not creating a new string every time, in this case IMO it's preferable to keep the value in Memory and return always the same instance. What do y thin?

2024-01-30 14:51 UTC, anna-naumova25 commented
> Thanks @anna-naumova25 looks good - the only thing for me - which we need to discuss is the GetAllAsync - I think should use SEARCHFILTER and ORDERBY options to build on the fly GET ODATA querys to filter and order the returning dataset - but this needs to be agreed for a future PR probably - thanks DanHo

Let's see if we can use Simple.OData.Client
https://www.odata.org/blog/advanced-odata-tutorial-with-simple-odata-client/
https://www.nuget.org/packages/Simple.OData.Client/

2024-01-30 15:36 UTC, anna-naumova25 commented on samples/Cryptocash.Ui/Nox.Generated/Ui.Services/EndpointsProvider.g.cs
> +        get { return $"{BaseUrl}/api"; }
as discussed, will be done in scope of NOX-650

2024-01-30 15:41 UTC, rochar commented on samples/Cryptocash.Ui/Nox.Generated/Ui.Services/EndpointsProvider.g.cs
> +public class EndpointsProvider
Should Abstract, and request the Interface in the DI

2024-01-30 15:53 UTC, anna-naumova25 commented on src/Nox.Generator.Tasks/Ui/Extensions/ServiceCollectionExtension.scriban-cs
> +        services.AddSingleton<GlobalDataService>();
updated

2024-01-30 15:53 UTC, anna-naumova25 commented on src/Nox.Generator.Tasks/Ui/Extensions/ServiceCollectionExtension.scriban-cs
> +        services.AddMudServices();
updated

2024-01-30 15:53 UTC, anna-naumova25 commented on samples/Cryptocash.Ui/Nox.Generated/Ui.Extensions/ServiceCollectionExtension.g.cs
> +        services.AddScoped<EndpointsProvider>();
updated

2024-01-30 15:53 UTC, anna-naumova25 commented on samples/Cryptocash.Ui/Nox.Generated/Ui.Services/EndpointsProvider.g.cs
> +public class EndpointsProvider
updated

2024-01-30 16:14 UTC, rochar approved these changes

2024-01-31 08:48 UTC, DanielHodgeGH approved these changes

2024-01-31 08:48 UTC, merged