Fix NOX Issue#667
NoxOrg/Nox pull request #1406
Opened 2024-01-31 14:22 UTC by ahmedtolba1984

This PR to fix NOX Issue-667, Guid id is parsed incorrectly for ApiRoutingMapping

2024-02-21 11:07 UTC, rochar requested changes
looks good, just remove the unnecessary change in csproj

2024-02-21 11:07 UTC, rochar commented on tests/Nox.ClientApi.Tests/Nox.ClientApi.Tests.csproj
> +	<ItemGroup>
I guess this was left over. all changes on the csproj should be undone.

2024-02-22 11:48 UTC, ahmedtolba1984 commented
> looks good, just remove the unnecessary change in csproj

Done

2024-02-23 10:50 UTC, rochar approved these changes

2024-02-23 10:51 UTC, merged