MP-8521: NOX - Factory for converting Primitive types into Nox types …
NoxOrg/Nox pull request #567
Opened 2023-08-16 13:39 UTC by originalethanhunt

…for "DateTimeDuration"

2023-08-21 11:37 UTC, dejobratic requested changes

2023-08-21 11:37 UTC, dejobratic commented on src/Nox.Lib/Factories/Types/NoxTypeDateTimeDurationFactory .cs
Can we also update the EntityMapper.template file with this type?

2023-08-22 10:52 UTC, rochar approved these changes

2023-08-22 11:01 UTC, gjorgji-grgovski-authoritypartners approved these changes

2023-08-22 11:12 UTC, merged