Feature/localization consolidation
NoxOrg/Nox pull request #591
Opened 2023-08-18 09:33 UTC by jan-schutte

2023-08-18 13:53 UTC, rochar requested changes
looks good, we can discuss in more detail if y want

2023-08-18 13:53 UTC, rochar commented on src/Nox.Localization.SqlServer/Nox.Localization.SqlServer.csproj
So can we also join all this projects in Nox.Localization?

2023-08-18 13:53 UTC, rochar commented on src/Nox.Localization/DbContext/NoxLocalizationDbContext.cs
>      protected override void OnModelCreating(ModelBuilder modelBuilder)
do you want to delete this method, everything is commented, and we are not going by this path?

2023-08-18 13:53 UTC, rochar commented on src/Nox.Localization/Nox.Localization.csproj
> +    <ItemGroup>
I did not verify, but this dependency seems that it should not be needed? can you confirm?

2023-08-18 13:53 UTC, rochar commented on src/Nox.Localization/Nox.Localization.csproj
> +        <ProjectReference Include="..\Nox.EntityFramework.Sqlite\Nox.EntityFramework.Sqlite.csproj" />
yup... so lets add all Localization projects to Nox.Localization we are ok in bringing all dependencies, so....

2023-08-18 13:53 UTC, rochar commented on src/SampleWebApp/Controllers/WeatherForecastController.cs
I guess this was a merge conflict, you can delete [WeatherForecastController.cs]

2023-08-18 13:53 UTC, rochar commented on tests/Nox.Localization.SqlServer.Tests/Nox.Localization.SqlServer.Tests.csproj
so following the same idea, can we have a single Localization.Tests project?

2023-08-28 13:44 UTC, jan-schutte commented on src/Nox.Localization.SqlServer/Nox.Localization.SqlServer.csproj
Merged DB context into Nox entity store

2023-09-27 07:32 UTC, rochar commented
close, until we get back to localization

2023-09-27 07:32 UTC, closed without merging