MP-8784: Added the following types to allnoxtype entity
NoxOrg/Nox pull request #597
Opened 2023-08-19 07:39 UTC by originalethanhunt

Color
HtmlField
InternetDomainField
IpAddressField
JsonField
JwtTokenField
MonthField
NuidField

2023-08-19 08:18 UTC, rochar commented on src/Nox.Types.Abstractions/Enums/NoxType.cs
> +    [SimpleType(typeof(byte[]))]
@gjorgji-grgovski-authoritypartners we will keep Color as string in dtos?

2023-08-21 07:11 UTC, andresharpe commented on src/Nox.Types.Abstractions/Enums/NoxType.cs
> +    [SimpleType(typeof(byte[]))]
I think we should keep this simple and persist as a string in well known hex format, eg.:

#CD5C5C

2023-08-21 07:12 UTC, andresharpe commented on src/Nox.Types.Abstractions/Enums/NoxType.cs
> +    [SimpleType(typeof(byte[]))]
so it'll map to varchar(7) in sql server

2023-08-21 08:00 UTC, originalethanhunt commented on src/Nox.Types.Abstractions/Enums/NoxType.cs
> +    [SimpleType(typeof(byte[]))]
it's ARGB so I guess that will be varchar(9).

2023-08-21 09:05 UTC, rochar requested changes

2023-08-21 09:05 UTC, rochar commented on src/Nox.Types.Abstractions/Enums/NoxType.cs
> +    [SimpleType(typeof(byte[]))]
so lets make this string again, so we can merge this PR

@gjorgji-grgovski-authoritypartners  is taking care of creating a tickets to refactor Color Value Object to be string and a converter to varchar(9)

2023-08-21 09:05 UTC, rochar commented
Please also update it from main

2023-08-23 13:11 UTC, rochar approved these changes

2023-08-23 13:14 UTC, merged