Issues/655 relationship keys validation
NoxOrg/Nox pull request #722
Opened 2023-09-06 12:17 UTC by AndreyDegtyarev

Provided validation rules for relationships.
Introduced validator EntityRelationshipKeysValidator

2023-09-06 16:30 UTC, rochar requested changes
looks good, just some comments

2023-09-06 16:30 UTC, rochar commented on src/Nox.Solution/ValidationResources.resx
> +    <value>Owned entity {0} with ZeroOrOne or ExactlyOne relationship keys must be null</value>
```suggestion
    <value>Owned entity {0} with ZeroOrOne or ExactlyOne relationship can not have key(s).</value>
```

2023-09-06 16:30 UTC, rochar commented on src/Nox.Solution/ValidationResources.resx
> +    <value>Keys are mandatory for entity {0} if only it's not Owned entity with ZeroOrOne or ExactlyOne relationship keys.</value>
```suggestion
    <value>Keys are mandatory for entity {0}. Except owned entities with ZeroOrOne or ExactlyOne relationships.</value>
```

2023-09-06 16:30 UTC, rochar commented on src/Nox.Solution/Validation/Domain/EntityValidator.cs
> +            RuleForEach(e => e.OwnedRelationships)
should apply to OwnedRelationships and Relationships

2023-09-07 08:30 UTC, AndreyDegtyarev commented on src/Nox.Solution/Validation/Domain/EntityValidator.cs
> +            RuleForEach(e => e.OwnedRelationships)
Applied for Relationships as well, but it's not shown in comment differences.

2023-09-07 10:36 UTC, rochar approved these changes

2023-09-07 10:36 UTC, merged