Add automatic release each day
NoxOrg/Nox pull request #756
Opened 2023-09-11 08:41 UTC by ILoveMyTortoise

2023-09-11 10:31 UTC, rochar requested changes

2023-09-11 10:31 UTC, rochar commented on .github/workflows/automatic-release.yml
> +      - name: Get next version
we are using gitversion for computing, can we use the same

2023-09-11 10:31 UTC, rochar commented on .github/workflows/automatic-release.yml
> +          title: "${{ steps.versioning.outputs.version }}"
add the v to version

2023-09-12 12:45 UTC, ILoveMyTortoise commented on .github/workflows/automatic-release.yml
> +      - name: Get next version
done

2023-09-12 12:52 UTC, rochar approved these changes

2023-09-12 12:52 UTC, rochar commented on .github/workflows/automatic-release.yml
> +  push:
we can remove push to main for now

2023-09-12 12:52 UTC, merged