Fix test and database configurator
NoxOrg/Nox pull request #895
Opened 2023-10-02 13:56 UTC by ILoveMyTortoise

closes #853

2023-10-02 16:21 UTC, rochar submitted a review, later dismissed

2023-10-03 07:11 UTC, rochar requested changes

2023-10-03 07:11 UTC, rochar commented on src/Nox.Types.EntityFramework/Types/AutoNumber/AutoNumberDatabaseConfigurator.cs
> +            entity.Attributes.Any(x => x.Name.Equals(property.Name, StringComparison.OrdinalIgnoreCase) && x.Type == property.Type);
```suggestion
        var shouldAutoincrement = isKey ||   entity.Attributes.Any(x => x.Name.Equals(property.Name, StringComparison.OrdinalIgnoreCase) && x.Type == property.Type);
```

2023-10-03 07:11 UTC, rochar commented on src/Nox.Types.EntityFramework/Types/AutoNumber/AutoNumberDatabaseConfigurator.cs
> +        // If it's a foreign key of entit id type or relationship it shouldn't be auto-incremented.
```suggestion
        // If is normal attribute also set auto-incremented.
         // else If it's a foreign key of entit id type or relationship it shouldn't be auto-incremented.
```

2023-10-03 09:08 UTC, alexandervlasenko submitted a review, later dismissed

2023-10-03 09:13 UTC, AndreyDegtyarev commented on tests/Nox.Integration.Tests/Fixtures/NoxTestDataContextFixtureBase.cs
> +    protected Mock<IPublisher> _publisherFixture;
Readonly

2023-10-03 09:13 UTC, AndreyDegtyarev approved these changes, later dismissed

2023-10-03 13:17 UTC, rochar approved these changes

2023-10-03 13:37 UTC, merged