MP-9440 - Generate Documentation for Integration Events
NoxOrg/Nox pull request #920
Opened 2023-10-06 08:11 UTC by dejobratic

NOT READY FOR REVIEW

2023-10-09 15:13 UTC, gjorgji-grgovski-authoritypartners approved these changes, later dismissed

2023-10-09 18:44 UTC, gjorgji-grgovski-authoritypartners submitted a review, later dismissed

2023-10-10 14:25 UTC, rochar requested changes
looks good, one comment to review

2023-10-10 14:25 UTC, rochar commented on src/Nox.Docs/Extensions/ScribanTemplateExtensions.cs
@dejobratic I think we could reuse the `NoxSolutionBridge` that is on Nox.Generator
I would be ok to add a dependency to Nox.Generator

Even this code   

```
 var scriptObj = new ScriptObject();
        scriptObj.Import(model, renamer: member => member.Name, filter: null);
```

it's also being used in the TemplateCodeBuilder.GenerateSourceCode we could probably add to NoxSolutionBridge (maybe rename this), and use in both sides

BTW we are creating a TemplateFileBuilder, in the feature we need to reassess if make sense the diverged path we are taking in both of the sides

2023-10-11 09:10 UTC, rochar approved these changes

2023-10-11 09:11 UTC, merged