MP-9075 NOX - Refactor EntityControllerGenerator to use Scriban template - Migrating endpoints for Entity
NoxOrg/Nox pull request #963
Opened 2023-10-11 13:40 UTC by emir-sehovic1

2023-10-13 06:52 UTC, rochar requested changes
looks good @emir-sehovic1 , juts two comments to considerer

2023-10-13 06:52 UTC, rochar commented on src/Nox.Generator/Common/TemplateScriptsBridges/NoxSolutionBridge.cs
> +        var scriptObject9 = new ScriptObject();
see https://github.com/scriban/scriban/blob/master/doc/builtins.md#string-functions, thera are scriban native functions, we may remove this

2023-10-13 06:52 UTC, rochar commented on src/Nox.Generator/Common/TemplateScriptsBridges/NoxSolutionBridge.cs
> +        var scriptObject11 = new ScriptObject();
this is only related with API Generator and the `PrimaryKeysFromRoute `can be done directly on the template so its clear what we are generating

and the same for this function `PrimaryKeysQuery`

2023-10-13 06:52 UTC, rochar commented on src/Nox.Generator/Common/TemplateScriptsBridges/NoxSolutionBridge.cs
> +        var scriptObject11 = new ScriptObject();
@emir-sehovic1  To keep it simple and move forward with the PR, lets add the result of this 2 function to the generator class, so its only available for this template

```
  new TemplateCodeBuilder(context, codeGeneratorState)
      .WithClassName($"{entity.PluralName}Controller")
      .WithFileNamePrefix("Presentation.Api.OData")
      .WithFileNameSuffix("Entity")
      .WithObject("entity", entity)
     .WithObject("PrimaryKeysQuery", GetPrimaryKeysQuery())
    ...
```

2023-10-13 06:52 UTC, rochar commented on src/Nox.Generator/Common/TemplateScriptsBridges/NoxSolutionBridge.cs
> +        var scriptObject9 = new ScriptObject();
that way we can remove the link to string build extensions

2023-10-16 13:18 UTC, rochar approved these changes

2023-10-17 08:13 UTC, gjorgji-grgovski-authoritypartners approved these changes

2023-10-17 08:13 UTC, merged