Change topic name logic
NoxOrg/Nox pull request #981
Opened 2023-10-12 12:26 UTC by ILoveMyTortoise

2023-10-13 14:32 UTC, rochar requested changes
looks good just a few suggestions

2023-10-13 14:32 UTC, rochar commented on src/Nox.Lib/Infrastructure/Messaging/AzureServiceBus/CustomEntityNameFormatter.cs
> +                throw new UnknownMessageTypeException($"Unknown message type received. Message type: '{typeof(T)}'. Can't process message.");
```suggestion
                throw new UnknownMessageTypeException($"Unknown message type  {typeof(T)} received..");
```

2023-10-13 14:32 UTC, rochar commented on src/Nox.Lib/Infrastructure/Messaging/EventNameIsEmptyException.cs
> +﻿namespace Nox.Exceptions
```suggestion
﻿namespace Nox.Infrastructure.Messaging
```

2023-10-13 14:32 UTC, rochar commented on src/Nox.Lib/Infrastructure/Messaging/EventNameIsEmptyException.cs
> +﻿namespace Nox.Exceptions
I will update the other exceptions if they do not follow this rule

2023-10-13 14:32 UTC, rochar commented on src/Nox.Lib/Infrastructure/Messaging/EventTraitIsEmptyException.cs
> +﻿namespace Nox.Exceptions
```suggestion
﻿namespace Nox.Infrastructure.Messaging
```

2023-10-13 14:32 UTC, rochar commented on src/Nox.Lib/Infrastructure/Messaging/EventTraitIsEmptyException.cs
> +    public class EventTraitIsEmptyException : Exception
```suggestion
    public class EventTraitIsNotFoundException : Exception
```

just a suggestion

2023-10-13 14:32 UTC, rochar commented on src/Nox.Lib/Infrastructure/Messaging/UnknownMessageTypeException.cs
> +﻿namespace Nox.Exceptions
```suggestion
﻿namespace ﻿namespace Nox.Infrastructure.Messaging
```

2023-10-17 06:06 UTC, alexandervlasenko approved these changes

2023-10-17 09:08 UTC, rochar approved these changes

2023-10-17 09:08 UTC, merged